# This is a basic workflow to help you get started with Actions

on:  
  workflow_dispatch:
jobs:  
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest       
    steps:
    - name: checkout
      uses: actions/checkout@v2 
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_Deloitte}}
        enable-AzPSSession: true   
    - name: Invoke Powershell script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          ./Invoke_Failover_Storage_multi-values_param.ps1 -resource_group_name "${{vars.RESOURCE_GROUP_NAME}}" -storageaccount_names "${{vars.STORAGEACCOUNT_NAMES}}" -sku "${{vars.SKU}}"  
        azPSVersion: "latest"
